clone:
  skip_verify: true
build:
  image: node:argon
  environment:
    - NODE_ENV=test
  commands:
    - export GIT_SSL_NO_VERIFY=1
    - echo "The next command might download for a while in silence."
    - npm install --depth 0 --loglevel=error
    - npm run build
    - echo "Project passed all specs and built corretly!"
notify:
  hipchat:
    auth_token: xxxxxxxxxxxxxxx
    room_id_or_name: 1234567
    notify: true
    from: drone
